//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalcWPF.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddNumber", ReplyAction="http://tempuri.org/IService/AddNumberResponse")]
        double AddNumber(double number1, double number2, System.Guid myGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddNumber", ReplyAction="http://tempuri.org/IService/AddNumberResponse")]
        System.Threading.Tasks.Task<double> AddNumberAsync(double number1, double number2, System.Guid myGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SubNumber", ReplyAction="http://tempuri.org/IService/SubNumberResponse")]
        double SubNumber(double number1, double number2, System.Guid myGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SubNumber", ReplyAction="http://tempuri.org/IService/SubNumberResponse")]
        System.Threading.Tasks.Task<double> SubNumberAsync(double number1, double number2, System.Guid myGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/MultNumber", ReplyAction="http://tempuri.org/IService/MultNumberResponse")]
        double MultNumber(double number1, double number2, System.Guid myGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/MultNumber", ReplyAction="http://tempuri.org/IService/MultNumberResponse")]
        System.Threading.Tasks.Task<double> MultNumberAsync(double number1, double number2, System.Guid myGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DivNumber", ReplyAction="http://tempuri.org/IService/DivNumberResponse")]
        double DivNumber(double number1, double number2, System.Guid myGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DivNumber", ReplyAction="http://tempuri.org/IService/DivNumberResponse")]
        System.Threading.Tasks.Task<double> DivNumberAsync(double number1, double number2, System.Guid myGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SignChange", ReplyAction="http://tempuri.org/IService/SignChangeResponse")]
        double SignChange(double number1, System.Guid myGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SignChange", ReplyAction="http://tempuri.org/IService/SignChangeResponse")]
        System.Threading.Tasks.Task<double> SignChangeAsync(double number1, System.Guid myGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/HistoryReport", ReplyAction="http://tempuri.org/IService/HistoryReportResponse")]
        string[] HistoryReport(System.Guid myGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/HistoryReport", ReplyAction="http://tempuri.org/IService/HistoryReportResponse")]
        System.Threading.Tasks.Task<string[]> HistoryReportAsync(System.Guid myGuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : CalcWPF.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<CalcWPF.ServiceReference1.IService>, CalcWPF.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double AddNumber(double number1, double number2, System.Guid myGuid) {
            return base.Channel.AddNumber(number1, number2, myGuid);
        }
        
        public System.Threading.Tasks.Task<double> AddNumberAsync(double number1, double number2, System.Guid myGuid) {
            return base.Channel.AddNumberAsync(number1, number2, myGuid);
        }
        
        public double SubNumber(double number1, double number2, System.Guid myGuid) {
            return base.Channel.SubNumber(number1, number2, myGuid);
        }
        
        public System.Threading.Tasks.Task<double> SubNumberAsync(double number1, double number2, System.Guid myGuid) {
            return base.Channel.SubNumberAsync(number1, number2, myGuid);
        }
        
        public double MultNumber(double number1, double number2, System.Guid myGuid) {
            return base.Channel.MultNumber(number1, number2, myGuid);
        }
        
        public System.Threading.Tasks.Task<double> MultNumberAsync(double number1, double number2, System.Guid myGuid) {
            return base.Channel.MultNumberAsync(number1, number2, myGuid);
        }
        
        public double DivNumber(double number1, double number2, System.Guid myGuid) {
            return base.Channel.DivNumber(number1, number2, myGuid);
        }
        
        public System.Threading.Tasks.Task<double> DivNumberAsync(double number1, double number2, System.Guid myGuid) {
            return base.Channel.DivNumberAsync(number1, number2, myGuid);
        }
        
        public double SignChange(double number1, System.Guid myGuid) {
            return base.Channel.SignChange(number1, myGuid);
        }
        
        public System.Threading.Tasks.Task<double> SignChangeAsync(double number1, System.Guid myGuid) {
            return base.Channel.SignChangeAsync(number1, myGuid);
        }
        
        public string[] HistoryReport(System.Guid myGuid) {
            return base.Channel.HistoryReport(myGuid);
        }
        
        public System.Threading.Tasks.Task<string[]> HistoryReportAsync(System.Guid myGuid) {
            return base.Channel.HistoryReportAsync(myGuid);
        }
    }
}
